mode: debug
receivers:
- receiver@yufu.fun
notify:
  driver: mail
  url:  user | password | smtp.mxhichina.com | 25
files:
- file: ./test.log
  desc: 测试文件
  analyser: nginx
  rules:
  - rule: path/to.*(499|500)
    desc: http请求异常
    interval: 60s
    duration: 60s
    times: 5