mode: debug
receivers:
- receiver@yufu.fun
notify:
  driver: mail
  url:  user | password | smtp.mxhichina.com | 25
rules:
- file: ./test.log
  rule: path/to.*(499|500)
  desc: http请求异常
  duration: 60s